Add endpoint for allowing admins to force rotate a user's token
harness/drone pull request #3272
Opened 2022-10-10 11:47 UTC by ShiftedMr

**Reason**: Better security management as admins can force rotate a token if someone commits their token in plaintext somewhere.
**To Test**
0. Requires 2 user accounts for testing. 1 admin 1 nonadmin
1. `curl -X POST -H"Authorization: Bearer <admintoken>" <droneserver>/api/users/<nonadmin-username>/token/rotate
2. Go to <nonadmin-username>'s user page while logged in as them
3. Verify token rotated
4. `curl -X POST -H"Authorization: Bearer <nonadmintoken>" <droneserver>/api/users/<admin-username>/token/rotate 
5. Receive Error
6. Go to <admin-username>'s user page while logged in as them
7. Verify token did not rotate

### From Checklist: 
- [x] Commit is a single logical unit of work, only use multiple commits if doing different tasks
- [x] Commit does not include commented out code or unneeded files
- [x] Rebase of main branch

### The Content

- [x] Must include testing for bug or feature
- [ ] Must include appropriate documentation changes if it is introducing a new feature or changing existing functionality
- [x] Must pass existing test suites

### The Commit Message

- [x] Short meaningful description (ex: remove deprecated steps)
- [x] Uses the imperative, present tense: "change", not "changed" or "changes"
- [x] Includes motivation for the change, and contrasts its implementation with the previous behavior

### The Pull Request

- [x] What is the reason for this change
- [x] Example usage of the failure for a bug, or configuration and expected output for a feature
- [x] Steps to test the change

2022-10-10 11:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/drone?pullRequest=3272) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/drone?pullRequest=3272) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/drone?pullRequest=3272) it.</sub>

2022-10-25 09:32 UTC, eoinmcafee00 approved these changes

2022-10-25 09:32 UTC, eoinmcafee00 requested changes
hey @ShiftedMr 
Why is this tested comment out?

2022-10-26 12:07 UTC, ShiftedMr commented
Hi @eoinmcafee00,
Thanks I somehow didn't realize I forgot to finish that. I fixed that and added a Usernotfound test.

2022-10-26 12:12 UTC, eoinmcafee00 approved these changes

2022-10-26 12:13 UTC, merged